Build git under python 2
Got this stack trace on circle-ci.  Guess I need to build git in python
2 only

make[2]: Leaving directory `/opt/conda/conda-bld/work'
    ASCIIDOC git-add.html
  File "/usr/bin/asciidoc", line 95
    except KeyError, k: return None
                   ^
SyntaxError: invalid syntax
make[1]: *** [git-add.html] Error 1
make[1]: Leaving directory `/opt/conda/conda-bld/work/Documentation'
make: *** [doc] Error 2