MNT: Add CONDA_NPY=110 flag to fix stack trace
Error: Failed to render jinja template in /tmp/edill/auto-build-tagged-recipes/sort-of-dev-but-actually-tag/py3/hkl-next/meta.yaml:
'dict object' has no attribute 'GIT_DESCRIBE_TAG'
Traceback (most recent call last):
  File "/tmp/edill/ramdisk/mc/bin/conda-build-all", line 9, in <module>
    load_entry_point('conda-build-all', 'console_scripts', 'conda-build-all')()
  File "/tmp/edill/scitools/conda-build-all/conda_build_all/cli.py", line 85, in main
    b.main()
  File "/tmp/edill/scitools/conda-build-all/conda_build_all/builder.py", line 207, in main
    recipe_metas = self.fetch_all_metas()
  File "/tmp/edill/scitools/conda-build-all/conda_build_all/builder.py", line 150, in fetch_all_metas
    recipe_metas = sort_dependency_order(recipe_metas)
  File "/tmp/edill/scitools/conda-build-all/conda_build_all/builder.py", line 97, in sort_dependency_order
    meta.parse_again()
  File "/tmp/edill/conda/conda-build/conda_build/metadata.py", line 345, in parse_again
    self.meta = parse(self._get_contents(permit_undefined_jinja))
  File "/tmp/edill/conda/conda-build/conda_build/metadata.py", line 644, in _get_contents
    env.globals.update(context_processor(self, path))
  File "/tmp/edill/conda/conda-build/conda_build/jinja_context.py", line 65, in context_processor
    ctx = get_environ(m=initial_metadata)
  File "/tmp/edill/conda/conda-build/conda_build/environ.py", line 160, in get_dict
    d.update(meta_vars(m))
  File "/tmp/edill/conda/conda-build/conda_build/environ.py", line 253, in meta_vars
    d['PKG_BUILD_STRING'] = str(meta.build_id())
  File "/tmp/edill/conda/conda-build/conda_build/metadata.py", line 471, in build_id
    for ms in self.ms_depends():
  File "/tmp/edill/conda/conda-build/conda_build/metadata.py", line 444, in ms_depends
    ms = handle_config_version(ms, ver)
  File "/tmp/edill/conda/conda-build/conda_build/metadata.py", line 296, in handle_config_version
    raise RuntimeError("'%s' requires external setting" % ms.spec)
RuntimeError: 'numpy x.x' requires external setting