Remove old version of xray-vision.
It is not building and I am not going to spend time making it build.
Here's the error, for posterity

BUILD START: xray-vision-0.0.3-py35_0
Fetching package metadata: ........
Solving package specifications:
.................../tmp/edill/ramdisk/mc/lib/python3.5/site-packages/requests/packages/urllib3/connection.py:266:
SubjectAltNameWarning: Certificate for pergamon.cs.nsls2.local has no
`subjectAltName`, falling back to check for a `commonName` for now. This
feature is being removed by major browsers and deprecated by RFC 2818.
(See https://github.com/shazow/urllib3/issues/497 for details.)
  SubjectAltNameWarning
/tmp/edill/ramdisk/mc/lib/python3.5/site-packages/requests/packages/urllib3/connection.py:266:
SubjectAltNameWarning: Certificate for pergamon.cs.nsls2.local has no
`subjectAltName`, falling back to check for a `commonName` for now. This
feature is being removed by major browsers and deprecated by RFC 2818.
(See https://github.com/shazow/urllib3/issues/497 for details.)
  SubjectAltNameWarning

WARNING: conda-build appears to be out of date. You have version 1.19.0
but the
latest version is 1.19.0.post13. Run

conda update -n root conda-build

to get the latest version.

Error: Unsatisfiable package specifications.
Generating hint:
[      COMPLETE
]|##################################################| 100%

Hint: the following packages conflict with each other:
  - python 3.5*
  - distribute

Use 'conda info python' etc. to see the dependencies for each package.